### ISSUE TITLE
Upgrade EMF dependencies used which are 7 years old

### ISSUE THREAD

**Issue by apupier** [jboss-fuse/fuse-components#124]
using latest ones should allow to have it working with Java 11 and ensure that it is working with recent Eclipse versions.

**Comment by zhfeng** [comment]
@apupier It looks like we have [ENTESB-14191](https://issues.redhat.com/browse/ENTESB-14191) to upgrade the emf dependecies now. The latest one is https://download.eclipse.org/modeling/emf/emf/builds/release/latest/index.html
